version: '3.8'

services:
  app:
    container_name: nextjs14
    image: nextjs14
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - '3000:3002'